### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by LesterCheng** [BBaoVanC/smines#4]
https://github.com/BBaoVanC/smines/blob/d9dc06af7d41c1769153f67cea4c7ecd98c59a97/smines

Here is the gdb output on the segfault:

> Setting cols to 10
> Setting rows to 20
> Setting mines to 0
> Allocating tiles array
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x0000555555555499 in main () at smines.c:23
> 23          minefield->mines = 5;

See if you can figure the problem out based on the gdb output, otherwise Andy and I can walk you through it tomorrow.

**Comment by BBaoVanC** [comment]
I went through it in gdb and it looks like in [minefield.c:19](https://github.com/BBaoVanC/smines/blob/95c00869d16b499b94f78670df77c3b2381abc98/minefield.c#L19) it's allocating minefield locally inside init_minefield, but not globally. After init_minefield is done, minefield is NULL (like it was set earlier in smines.c).

**Comment by LesterCheng** [comment]
Good catch! Thoughts on solutions?
